### ISSUE TITLE
Is the ios app code available?

### ISSUE THREAD

**Issue by imobiledev** [HoyosIntegrity/V.ALRT-ios#1]
Hello,

I’m working to integrate your V.ALRT button into my Objc iOS app and was wondering if you plan to upload your iOS app code to your GitHub as sample code?

https://github.com/HoyosIntegrity/V.ALRT-ios

Thank you,

Mike

**Comment by annerajb** [comment]
It's on the plans for this week. Subscribe to the repo and you should get a
notification when it's pushed.

**Comment by imobiledev** [comment]
Awesome!! Thank you very much. 

Will it be swift or objc?

**Comment by annerajb** [comment]
It's all objc but we are including a untested bridging header.

**Comment by ghost** [comment]
Hello @imobiledev,

The iOS app has been uploaded. Marking issue as closed.
